

-- Jelantara schema for Supabase
-- Jalankan di Supabase SQL Editor pada project baru.

-- Profil tambahan untuk akun Supabase Auth.
-- Email tetap disimpan di auth.users dan dibaca dari sana.
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    phone TEXT,
    pickup_address TEXT,
    points_balance INTEGER NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Transaksi setor: data estimasi dan hasil verifikasi disimpan terpisah.
CREATE TABLE IF NOT EXISTS public.oil_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    transaction_code TEXT NOT NULL UNIQUE,
    liters NUMERIC(8,2) NOT NULL CHECK (liters > 0),
    estimated_price_per_liter INTEGER NOT NULL DEFAULT 7000 CHECK (estimated_price_per_liter >= 0),
    estimated_total_price INTEGER NOT NULL DEFAULT 0 CHECK (estimated_total_price >= 0),
    estimated_points INTEGER NOT NULL DEFAULT 0 CHECK (estimated_points >= 0),
    final_liters NUMERIC(8,2) CHECK (final_liters IS NULL OR final_liters > 0),
    final_price_per_liter INTEGER CHECK (final_price_per_liter IS NULL OR final_price_per_liter >= 0),
    final_total_price INTEGER CHECK (final_total_price IS NULL OR final_total_price >= 0),
    points_awarded INTEGER NOT NULL DEFAULT 0 CHECK (points_awarded >= 0),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'success', 'rejected')),
    method TEXT NOT NULL
        CHECK (method IN ('Dijemput Petugas', 'Antar ke Pusat')),
    rejection_reason TEXT,
    notes TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id, user_id)
);

-- Jadwal terkait transaksi; alamat disalin agar riwayat tetap utuh
-- walaupun alamat utama profil kemudian berubah.
CREATE TABLE IF NOT EXISTS public.pickup_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    scheduled_date DATE NOT NULL,
    time_slot TEXT NOT NULL
        CHECK (time_slot IN ('08.00 – 10.00', '10.00 – 12.00', '13.00 – 15.00', '15.00 – 17.00')),
    address TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled'
        CHECK (status IN ('scheduled', 'completed', 'cancelled')),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (transaction_id, user_id)
        REFERENCES public.oil_transactions(id, user_id) ON DELETE CASCADE
);

-- Katalog reward yang ditampilkan pada halaman Reward.
CREATE TABLE IF NOT EXISTS public.rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    points_required INTEGER NOT NULL CHECK (points_required > 0),
    icon TEXT,
    category TEXT NOT NULL CHECK (category IN ('eco', 'rumah', 'voucher')),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Riwayat penukaran reward, termasuk snapshot nama dan poin saat ditukar.
CREATE TABLE IF NOT EXISTS public.reward_redemptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reward_id BIGINT NOT NULL REFERENCES public.rewards(id) ON DELETE RESTRICT,
    reward_name TEXT NOT NULL,
    points_spent INTEGER NOT NULL CHECK (points_spent > 0),
    status TEXT NOT NULL DEFAULT 'requested'
        CHECK (status IN ('requested', 'processed', 'completed', 'cancelled')),
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    notes TEXT
);

-- Otomatis buat profil ketika akun baru dibuat di Supabase Auth.
CREATE OR REPLACE FUNCTION public.create_profile_for_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, phone)
    VALUES (
        NEW.id,
        COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'full_name', ''), NULLIF(split_part(COALESCE(NEW.email, ''), '@', 1), ''), 'Pengguna Jelantara'),
        NULLIF(NEW.phone, '')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.create_profile_for_new_user();

-- updated_at otomatis diperbarui saat row diubah.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS oil_transactions_set_updated_at ON public.oil_transactions;
CREATE TRIGGER oil_transactions_set_updated_at BEFORE UPDATE ON public.oil_transactions
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS pickup_schedules_set_updated_at ON public.pickup_schedules;
CREATE TRIGGER pickup_schedules_set_updated_at BEFORE UPDATE ON public.pickup_schedules
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS rewards_set_updated_at ON public.rewards;
CREATE TRIGGER rewards_set_updated_at BEFORE UPDATE ON public.rewards
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Indeks untuk riwayat per user dan filter yang dipakai website.
CREATE INDEX IF NOT EXISTS idx_oil_transactions_user_created
    ON public.oil_transactions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_oil_transactions_status
    ON public.oil_transactions (status);
CREATE INDEX IF NOT EXISTS idx_pickup_schedules_user_date
    ON public.pickup_schedules (user_id, scheduled_date);
CREATE INDEX IF NOT EXISTS idx_rewards_category_active
    ON public.rewards (category, is_active);
CREATE INDEX IF NOT EXISTS idx_reward_redemptions_user_date
    ON public.reward_redemptions (user_id, redeemed_at DESC);

-- Reward awal sesuai katalog yang tampil di website. Aman dijalankan ulang.
INSERT INTO public.rewards
    (id, code, name, description, points_required, icon, category, stock)
VALUES
    (1, 'eco-bottle', 'Eco Bottle', 'Botol minum ramah lingkungan dari bahan daur ulang.', 1200, '🧴', 'eco', 20),
    (2, 'reusable-bag', 'Reusable Bag', 'Tas belanja yang bisa dipakai berulang kali.', 800, '👜', 'eco', 30),
    (3, 'sabun-jelantah', 'Sabun dari Jelantah', 'Sabun organik dari minyak jelantah daur ulang.', 1000, '🧼', 'rumah', 15),
    (4, 'voucher-belanja', 'Voucher Belanja', 'Voucher Rp50.000 di merchant mitra Jelantara.', 1500, '🎫', 'voucher', 12),
    (5, 'tote-bag-jelantara', 'Tote Bag Jelantara', 'Tote bag eksklusif desain Jelantara.', 900, '🛍️', 'eco', 18),
    (6, 'voucher-pulsa', 'Voucher Pulsa', 'Voucher pulsa Rp25.000 semua operator.', 750, '📱', 'voucher', 25)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    points_required = EXCLUDED.points_required,
    icon = EXCLUDED.icon,
    category = EXCLUDED.category,
    stock = EXCLUDED.stock,
    is_active = TRUE;

SELECT setval(
    pg_get_serial_sequence('public.rewards', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.rewards), 1),
    TRUE
);

-- Row Level Security: data user hanya dapat dibaca/dibuat oleh pemiliknya.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oil_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pickup_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_redemptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Read own profile" ON public.profiles;
CREATE POLICY "Read own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Update own profile" ON public.profiles;
CREATE POLICY "Update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Read own transactions" ON public.oil_transactions;
CREATE POLICY "Read own transactions" ON public.oil_transactions
    FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Create own transactions" ON public.oil_transactions;
CREATE POLICY "Create own transactions" ON public.oil_transactions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Read own pickup schedules" ON public.pickup_schedules;
CREATE POLICY "Read own pickup schedules" ON public.pickup_schedules
    FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Create own pickup schedules" ON public.pickup_schedules;
CREATE POLICY "Create own pickup schedules" ON public.pickup_schedules
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can read active rewards" ON public.rewards;
CREATE POLICY "Anyone can read active rewards" ON public.rewards
    FOR SELECT USING (is_active = TRUE);

DROP POLICY IF EXISTS "Read own reward redemptions" ON public.reward_redemptions;
CREATE POLICY "Read own reward redemptions" ON public.reward_redemptions
    FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Create own reward redemptions" ON public.reward_redemptions;
CREATE POLICY "Create own reward redemptions" ON public.reward_redemptions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Total transaksi dan liter disarankan dihitung dari oil_transactions.
-- Email profil tersedia di auth.users; poin aktif tersimpan di profiles.points_balance.
-- Validasi saldo poin dan perubahan status/harga final sebaiknya dilakukan server-side.
